//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTPN
    {
        public string maCTPN { get; set; }
        public string maPhieuNhap { get; set; }
        public string maSach { get; set; }
        public int soLuong { get; set; }
        public long donGia { get; set; }
        public long thanhTien { get; set; }
    
        public virtual tb_PhieuNhap tb_PhieuNhap { get; set; }
        public virtual tb_Sach tb_Sach { get; set; }
    }
}
