//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_NguoiDung
    {
        [Required]
        [StringLength(maximumLength:10,MinimumLength =5,ErrorMessage ="Nhập từ 5 đến 10 kí tự")]
        public string TaiKhoan { get; set; }

        [Required]
        [StringLength(maximumLength: 10, MinimumLength = 5, ErrorMessage = "Nhập từ 5 đến 10 kí tự")]

        public string MatKhau { get; set; }
    }
}
