//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PhieuNhap()
        {
            this.tb_CTPN = new HashSet<tb_CTPN>();
        }
    
        public string maPhieuNhap { get; set; }
        public string maNXB { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public long thanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTPN> tb_CTPN { get; set; }
        public virtual tb_NXB tb_NXB { get; set; }
    }
}
