//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTPX
    {
        public string maCTPX { get; set; }
        public string maPhieuXuat { get; set; }
        public string maSach { get; set; }
        public int soLuong { get; set; }
        public long thanhTien { get; set; }
    
        public virtual tb_PhieuXuat tb_PhieuXuat { get; set; }
    }
}
