//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QLSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_NguoiDung
    {
        [Required(ErrorMessage ="Không được để trống")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string MatKhau { get; set; }
    }
}
